# Generated by Django 2.2.2 on 2021-05-22 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAuth',
            new_name='UserInfo',
        ),
    ]
