# Generated by Django 2.2.2 on 2021-05-25 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_companyinfo_companylocation_companytest_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinfo',
            name='address',
        ),
        migrations.AddField(
            model_name='companylocation',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
