# Generated by Django 2.2.2 on 2021-05-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210525_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companytest',
            name='test',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
