# Generated by Django 2.2.2 on 2021-05-25 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210525_1153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companytest',
            old_name='test',
            new_name='test_name',
        ),
    ]
