# Generated by Django 2.2.2 on 2021-05-25 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210525_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companytest',
            old_name='test_name',
            new_name='test',
        ),
    ]
